name: Actions Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet   # The id is created to refrence a particular step 
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: John #creating input
      
      - name: Log Greeting Time
        run: echo "${{steps.greet.output.time}}" # using id to call the previous step


