name: Shell Commands

on: push

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo " Hello world"

      - name: multi script
        run: |
          node -v
          npm -v
      
      - name: python Command  #(trying to use another shell)
        run: |
          import platform
          print(platform.processor())
        shell: python

#new job starts here
  run-windows-commands:
    run-on: windows-latest
    steps: 
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash